name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm run make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            out/make/rpm/x64/id-electron-*-x86_64.rpm
            out/make/deb/x64/id-electron_*_amd64.deb
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm run make:windows
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: out/make/zip/x64/id-electron-win32-x64-*.zip
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm run make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: out/make/zip/x64/id-electron-darwin-x64-*.zip